### ISSUE TITLE
Непонятная ошибка

### ISSUE THREAD

**Issue by YXMVKXR** [imDaniX/WGExtender#6]
Запускается сервер и плагин, выходит ошибка, возможна она не связана с WGex, но, проверь, пожалуйста. Про этом все отлично работает, без ошибок, но ошибка была дважды. Других ошибок нет, процессов вроде также не было. Ошибка похожа на ядро, ибо ничего не сказано о плагинах, но, это также дело не в ядре. Используется также плагин PlugManX, может в нем проблема, но, не знаю даже. 

[16:50:47 INFO]: [WGExtender] Loading server plugin WGExtender v3.1.1-fork
[16:50:47 INFO]: [WGExtender] Enabling WGExtender v3.1.1-fork
[16:50:47 ERROR]: Caught previously unhandled exception :
[16:50:47 ERROR]: Paper Async Command Builder Thread Pool - 2
java.util.ConcurrentModificationException: null
        at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1023) ~[?:?]
        at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:1052) ~[?:?]
        at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:547) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.commands.Commands.sendAsync(Commands.java:504) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.commands.Commands.lambda$sendCommands$5(Commands.java:483) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:50:47 ERROR]: Caught previously unhandled exception :
[16:50:47 ERROR]: Paper Async Command Builder Thread Pool - 3
java.util.ConcurrentModificationException: null
        at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1023) ~[?:?]
        at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:1052) ~[?:?]
        at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:547) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.commands.Commands.sendAsync(Commands.java:504) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.commands.Commands.lambda$sendCommands$5(Commands.java:483) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by imDaniX** [comment]
Дело *скорее всего* в WGEx, но если честно, пока не могу придумать, как избежать ошибку наверняка. Раз больше проблем не создаёт, то пока не в приоритете, но буду иметь в виду.

**Comment by GG-MD** [comment]
Согласен, тоже что-то такое бывает

**Comment by GG-MD** [comment]
up @imDaniX
